### ISSUE TITLE
Зависимости для пакета vibe-d неправильно заданы (dub.sdl) 

### ISSUE THREAD

**Issue by denizzzka** [deviator/restexample#1]

**Comment by denizzzka** [comment]
Добавил зависимость version="*" и сервер не собрался:

```
$ dub build --config=server
Performing "debug" build using dmd for x86_64.
vibe-d:utils 0.7.29: building configuration "library"...
vibe-d:data 0.7.29: building configuration "library"...
vibe-d:core 0.7.29: building configuration "libevent"...
vibe-d:http 0.7.29: building configuration "library"...
vibe-d:diet 0.7.29: building configuration "library"...
vibe-d:mail 0.7.29: building configuration "library"...
vibe-d:mongodb 0.7.29: building configuration "library"...
vibe-d:redis 0.7.29: building configuration "library"...
vibe-d:web 0.7.29: building configuration "library"...
vibe-d 0.7.29: building configuration "libevent"...
restexample ~master: building configuration "server"...
../../.dub/packages/vibe-d-0.7.29/vibe-d/source/vibe/web/rest.d(252,26): Error: template vibe.web.rest.serveRestJSClient cannot deduce function from argument types !()(RestInterfaceSettings), candidates are:
../../.dub/packages/vibe-d-0.7.29/vibe-d/source/vibe/web/rest.d(213,27):        vibe.web.rest.serveRestJSClient(I)(RestInterfaceSettings settings) if (is(I == interface))
../../.dub/packages/vibe-d-0.7.29/vibe-d/source/vibe/web/rest.d(241,27):        vibe.web.rest.serveRestJSClient(I)(URL base_url)
../../.dub/packages/vibe-d-0.7.29/vibe-d/source/vibe/web/rest.d(248,27):        vibe.web.rest.serveRestJSClient(I)(string base_url)
source/app.d(16,57): Error: template instance vibe.web.rest.serveRestJSClient!(IModel) error instantiating
Compiling diet template 'index.dt'...
dmd failed with exit code 1.
```

(клиент собирается ок)

**Comment by denizzzka** [comment]
Вообще, я пытаюсь посмотреть как выглядит REST-ответ сервера, так что, если можете сдампать его то буду признателен)

**Comment by deviator** [comment]
да, согласен, просто я правил пару вопросов в vibe-d, связанных с rest, [pr](https://github.com/rejectedsoftware/vibe.d/pull/1566)
прямо сейчас Вы можете использовать коммит f24a7e0d066dfd7d2b3b7a68869124baee7820a8 (предыдущий с комментарием final)
через несколько минут откачу состояние репозитария, чтобы можно было собирать из head

**Comment by deviator** [comment]
@denizzzka REST ответ в теле содержит сериализованный тип данных, возвращаемый методом интерфейса (если это строка, то она в двойных кавычках, если число -- без кавычек, если структура, то как json-объект), content-type application/json и, кажется, всё.

Код, который выдал у Вас ошибку, натыкается на баг в текущей реализации vibe-d (даже не баг, а просто недоразумение: забыли инстанцировать основной метод serveRestJSClient внутри перегруженного вспомогательного метода). Так же есть проблемы в генерации js клиента: 
1. методы, возвращающие интерфейсы неправильно преобразуются в js
2. параметры, передаваемые в url в get запросе не могут быть объектами, так как вписываются в строку url не верно
это поправлено в моём pull request, но пока он не одобрен
